### ISSUE TITLE
using arrow operator with SystemC peripheral GPIO

### ISSUE THREAD

**Issue by ky-macpherson** [antmicro/renode-systemc-examples#2]
Hi, I am having difficulty using the arrow operator to connect another peripheral IRQ to a SystemC peripheral GPIO.

For example I attempted to modify the dma example by adding these lines to **dma.repl**

```
uart0: UART.NS16550 @ sysbus <0x4005c000, +0x100>
    IRQ -> dma_systemc@2
```

But the arrow operator causes a crash on loading the repl file

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at Antmicro.Renode.Peripherals.SystemC.SystemCPeripheral.SendRequest (Antmicro.Renode.Peripherals.SystemC.RenodeMessage request) [0x00035] in <26819909300142849394e44221e7c891>:0
```

What is the right way to make this connection?  Thanks

**Comment by adrabarek** [comment]
Hi, thank you for reporting the issue. The usage you showed is correct; this is a bug in Renode. It seems like a trivial missing null value check, we should have it fixed shortly.

**Comment by adrabarek** [comment]
The fix to Renode is committed: https://github.com/renode/renode/commit/e21e55ba713723ca6f319c5169fd6a280e11f718

**Comment by ky-macpherson** [comment]
Great, thanks!  I can confirm this update resolves the issue
